---
title: Academic conduct
---

USC seeks to maintain an optimal learning environment. General principles of academic honesty include the concept of respect for the intellectual property of others, the expectation that individual work will be submitted unless otherwise allowed by an instructor, and the obligations both to protect one's own academic work from misuse by others as well as to avoid using another's work as one's own. All students are expected to understand and abide by these principles. <a href="http://scampus.usc.edu/">SCampus</a>, the Student Guidebook, contains the University Student Conduct Code (see University Governance, Section 11.00), while the recommended sanctions are located in Appendix A.

Plagiarism -- presenting someone else’s ideas as your own, either verbatim or recast in your own words -- is a serious academic offense with serious consequences.  Please familiarize yourself with the discussion of plagiarism in SCampus in <a href="https://scampus.usc.edu/1100-behavior-violating-university-standards-and-appropriate-sanctions">Section 11, Behavior Violating University Standards</a>.  Other forms of academic dishonesty are equally unacceptable.  See additional information in SCampus and <a href="http://policy.usc.edu/scientific-misconduct">university policies on scientific misconduct</a>. 

Discrimination, sexual assault, and harassment are not tolerated by the university.  You are encouraged to report any incidents to the <a href="http://equity.usc.edu">Office of Equity and Diversity</a> or to the <a href="http://adminopsnet.usc.edu/department/department-public-safety">Department of Public Safety</a>.  This is important for the safety of the whole USC community.  Another member of the university community -- such as a friend, classmate, advisor, or faculty member -- can help initiate the report, or can initiate the report on behalf of another person.  The <a href="http://www.usc.edu/student-affairs/cwm/ ">Center for Women and Men</a> provides 24/7 confidential support, and the <a href="http://sarc.usc.edu">Sexual Assault Resource Center webpage</a> describes reporting options and other resources.



