---
title: Support systems
---

A number of USC's schools provide support for students who need help with scholarly writing.  Check with your advisor or program staff to find out more.  Students whose primary language is not English should check with the <a href="http://dornsife.usc.edu/ali">American Language Institute</a>, which sponsors courses and workshops specifically for international graduate students. If an officially declared emergency makes travel to campus infeasible, <a href="http://emergency.usc.edu">USC Emergency Information</a> will provide safety and other updates, including ways in which instruction will be continued by means of blackboard, teleconferencing, and other technology.

The <a href="https://dsp.usc.edu/">Office of Disability Services and Programs</a> (DSP) provides certification for students with disabilities and helps arrange the relevant accommodations. Any student requesting academic accommodations based on a disability is required to register with DSP each semester. A letter of verification for approved accommodations can be obtained from DSP. Please be sure the letter is delivered to me as early in the semester as possible. DSP is located in STU 301 and is open 8:30 a.m. – 5:00 p.m., Monday through Friday. The phone number for DSP is (213) 740-0776.




